name: Jest Tests

on:
  push:
    branches:
      - main

jobs:
  test:
     runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}
     services:
        mongodb:
            image: mongo
            env:
              MONGO_INITDB_ROOT_USERNAME: test
              MONGO_INITDB_ROOT_PASSWORD: password
              MONGO_INITDB_DATABASE: test
            options: >-
              --health-cmd mongo
              --health-interval 10s
              --health-timeout 5s
              --health-retries 5
            ports:
              - 27017:27017
     steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.x
          cache: npm
        
      - name: Install dependencies
        run: npm install
  
      - name: Run Jest tests
        run: node --experimental-vm-modules  node_modules/jest/bin/jest.js --detectOpenHandles --forceExit
