name: Jest Tests

on:
  push:
    branches:
      - main

jobs:
  test:
     runs-on: ${{ fromJSON('["ubuntu-latest", "self-hosted"]')[github.repository == 'github/docs-internal'] }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.17.x
          cache: npm
      
      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: node --experimental-vm-modules node_modules/jest/bin/jest.js